version: "3.8"

services:
  mysqldb:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationski_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-stationski:
    depends_on:
      - mysqldb
    image: raedkharrat/gestion-station-ski:1.0
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationski_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'


    stdin_open: true
    tty: true

volumes:
  db :